### ISSUE TITLE
[BUG] version mismatched

### ISSUE THREAD

**Issue by favoyang** [OmiyaGames/template-unity-package#2]
### Describe the bug

Seems for all [releases](https://github.com/OmiyaGames/template-unity-package/releases), the version is v0.1.0-preview.1.

```
  "name": "com.omiyagames.template",
  ...
  "version": "0.1.0-preview.1",
```
#### Expected behavior

The version of package.json matched with their tag name. Otherwise, [all later builds](https://openupm.com/packages/com.omiyagames.template/) will be failed.

**Comment by japtar10101** [comment]
@favoyang You know, maybe I should just delete this package's info from OpenUPM.  Since this is meant to be a template, the package version number is intentionally left to 0.1.0-preview.1.  Honestly, it being up on OpenUPM is a complete accident: I don't actually recall how I uploaded it (pretty sure I meant to upload the Omiya Games - Global package instead).

**Comment by favoyang** [comment]
Got it. Thanks for the explanation.
